#!/bin/bash
# ============================================================
# EVA-SHELL — apply-theme.sh
# Phase 2: Theme Engine
# Usage: ./scripts/apply-theme.sh <theme-name>
#        ./scripts/apply-theme.sh eva-01
# ============================================================

set -e

EVA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEME_NAME="${1:-eva-01}"
THEME_DIR="$EVA_DIR/themes/$THEME_NAME"
COLORS="$THEME_DIR/colors.conf"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${CYAN}[THEME]${NC} $1"; }
ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ============================================================
# Validate theme exists
# ============================================================
[ -d "$THEME_DIR" ] || die "Theme '$THEME_NAME' not found at $THEME_DIR"
[ -f "$COLORS"    ] || die "colors.conf missing from theme $THEME_NAME"

log "Applying theme: $THEME_NAME"

# ============================================================
# Load all color variables
# ============================================================
source "$COLORS"

# ============================================================
# Helper: replace token in file
# Usage: inject_color <file> <token> <value>
# ============================================================
inject_color() {
    local file="$1"
    local token="$2"
    local value="$3"
    if [ -f "$file" ]; then
        sed -i "s|{{$token}}|$value|g" "$file"
    fi
}

# ============================================================
# Generate kitty theme
# ============================================================
log "Patching kitty config..."
KITTY_CONF="$EVA_DIR/config/kitty/kitty.conf"
cat > "$KITTY_CONF" << EOF
# EVA-SHELL — kitty.conf — Theme: $THEME_NAME
# Auto-generated by apply-theme.sh — DO NOT EDIT MANUALLY

font_family        $FONT_MAIN
bold_font          $FONT_MAIN Bold
italic_font        $FONT_MAIN Italic
font_size          $FONT_SIZE_NORMAL

background            $PRIMARY_BG
foreground            $TEXT_PRIMARY
cursor                $ACCENT_GREEN
cursor_text_color     $PRIMARY_BG

selection_background  $ACCENT_PURPLE
selection_foreground  $TEXT_PRIMARY

# Black
color0  $PRIMARY_BG
color8  $BORDER

# Red (errors)
color1  $ACCENT_ORANGE
color9  $ACCENT_ORANGE

# Green (ok / accent)
color2  $ACCENT_GREEN
color10 $STATUS_OK

# Yellow (warn)
color3  $STATUS_WARN
color11 $STATUS_WARN

# Blue (info)
color4  $MELCHIOR
color12 $MELCHIOR

# Magenta (purple)
color5  $ACCENT_PURPLE
color13 $ACCENT_PURPLE

# Cyan
color6  $ACCENT_CYAN
color14 $ACCENT_CYAN

# White
color7  $TEXT_PRIMARY
color15 $TEXT_PRIMARY

window_padding_width    6
hide_window_decorations yes
background_opacity      $OPACITY_PANEL
dynamic_background_color yes

# Performance
sync_to_monitor no
EOF
ok "kitty config written"

# ============================================================
# Generate i3 colors section (appended to main config)
# ============================================================
log "Patching i3 colors..."
I3_COLORS_FILE="$EVA_DIR/config/i3/colors.conf"
cat > "$I3_COLORS_FILE" << EOF
# EVA-SHELL — i3 color bindings — Theme: $THEME_NAME
# Auto-generated by apply-theme.sh

# class                 border          background      text            indicator       child_border
client.focused          $BORDER_ACTIVE  $SECONDARY_BG   $ACCENT_GREEN   $ACCENT_GREEN   $BORDER_ACTIVE
client.focused_inactive $BORDER         $PRIMARY_BG     $TEXT_DIM       $BORDER         $BORDER
client.unfocused        $PRIMARY_BG     $PRIMARY_BG     $TEXT_DIM       $PRIMARY_BG     $PRIMARY_BG
client.urgent           $ACCENT_ORANGE  $ACCENT_ORANGE  $PRIMARY_BG     $ACCENT_ORANGE  $ACCENT_ORANGE
client.placeholder      $PRIMARY_BG     $PRIMARY_BG     $TEXT_DIM       $PRIMARY_BG     $PRIMARY_BG
client.background       $PRIMARY_BG
EOF
ok "i3 colors written"

# ============================================================
# Generate polybar colors include
# ============================================================
log "Patching polybar colors..."
POLYBAR_COLORS="$EVA_DIR/config/polybar/colors.ini"
cat > "$POLYBAR_COLORS" << EOF
; EVA-SHELL — polybar colors — Theme: $THEME_NAME
; Auto-generated by apply-theme.sh

[colors]
bg          = $PRIMARY_BG
bg-panel    = $SECONDARY_BG
border      = $BORDER
border-act  = $BORDER_ACTIVE
fg          = $TEXT_PRIMARY
fg-dim      = $TEXT_DIM
fg-label    = $TEXT_LABEL
green       = $ACCENT_GREEN
purple      = $ACCENT_PURPLE
orange      = $ACCENT_ORANGE
cyan        = $ACCENT_CYAN
melchior    = $MELCHIOR
balthasar   = $BALTHASAR
caspar      = $CASPAR
ok          = $STATUS_OK
warn        = $STATUS_WARN
crit        = $STATUS_CRIT
EOF
ok "polybar colors written"

# ============================================================
# Generate eww scss variables
# ============================================================
log "Patching eww styles..."
EWW_VARS="$EVA_DIR/config/eww/_theme.scss"
cat > "$EWW_VARS" << EOF
// EVA-SHELL — eww theme variables — Theme: $THEME_NAME
// Auto-generated by apply-theme.sh

\$bg:           #{$PRIMARY_BG};
\$bg-panel:     #{$SECONDARY_BG};
\$border:       #{$BORDER};
\$border-act:   #{$BORDER_ACTIVE};
\$fg:           #{$TEXT_PRIMARY};
\$fg-dim:       #{$TEXT_DIM};
\$green:        #{$ACCENT_GREEN};
\$purple:       #{$ACCENT_PURPLE};
\$orange:       #{$ACCENT_ORANGE};
\$cyan:         #{$ACCENT_CYAN};
\$melchior:     #{$MELCHIOR};
\$balthasar:    #{$BALTHASAR};
\$caspar:       #{$CASPAR};
\$font:         "#{$FONT_MAIN}";
\$font-size:    #{$FONT_SIZE_NORMAL}px;
\$font-label:   #{$FONT_SIZE_LABEL}px;
EOF
ok "eww theme vars written"

# ============================================================
# Generate rofi theme
# ============================================================
log "Patching rofi config..."
mkdir -p "$EVA_DIR/config/rofi"
cat > "$EVA_DIR/config/rofi/eva.rasi" << EOF
/* EVA-SHELL — rofi theme — $THEME_NAME */
/* Auto-generated by apply-theme.sh     */

* {
    bg:         $PRIMARY_BG;
    bg-panel:   $SECONDARY_BG;
    border-col: $BORDER_ACTIVE;
    fg:         $TEXT_PRIMARY;
    fg-dim:     $TEXT_DIM;
    green:      $ACCENT_GREEN;
    purple:     $ACCENT_PURPLE;
    font:       "$FONT_MAIN $FONT_SIZE_NORMAL";
}

window {
    background-color: @bg;
    border:           2px solid;
    border-color:     @border-col;
    border-radius:    0px;
    width:            500px;
}

mainbox {
    background-color: transparent;
    padding:          8px;
}

inputbar {
    background-color: @bg-panel;
    text-color:       @green;
    border:           0 0 1px 0;
    border-color:     @border-col;
    padding:          8px;
    font:             "$FONT_MAIN Bold $FONT_SIZE_LARGE";
}

prompt { text-color: @purple; }
entry  { text-color: @green;  }

listview {
    background-color: transparent;
    padding:          4px 0;
    spacing:          2px;
}

element {
    background-color: transparent;
    text-color:       @fg-dim;
    padding:          6px 8px;
    border-radius:    0px;
}

element selected {
    background-color: @bg-panel;
    text-color:       @green;
    border:           0 0 0 2px;
    border-color:     @purple;
}

element-text { inherit; }
EOF
ok "rofi theme written"

# ============================================================
# Write current theme name to active marker
# ============================================================
echo "$THEME_NAME" > "$EVA_DIR/.active-theme"

# ============================================================
# Reload live components if i3 is running
# ============================================================
if pgrep -x i3 > /dev/null 2>&1; then
    log "i3 is running — reloading components..."

    # Reload i3
    i3-msg reload > /dev/null 2>&1 && ok "i3 reloaded" || warn "i3 reload failed"

    # Restart polybar
    if pgrep -x polybar > /dev/null 2>&1; then
        pkill polybar
        sleep 0.5
        polybar eva-top &
        ok "polybar restarted"
    fi

    # Restart eww
    if command -v eww &>/dev/null; then
        eww kill 2>/dev/null || true
        sleep 0.5
        eww daemon &
        ok "eww daemon restarted"
    fi
else
    log "i3 not running — configs ready for next session start"
fi

# ============================================================
# Done
# ============================================================
echo ""
echo -e "  ${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "  ${GREEN}║  THEME APPLIED: $THEME_NAME$(printf '%*s' $((22 - ${#THEME_NAME})) '')║${NC}"
echo -e "  ${GREEN}║  MAGI AESTHETIC: SYNCHRONIZED        ║${NC}"
echo -e "  ${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
